import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { useAuth } from '@/auth';
import { OwnerPropertySwitcher } from '@/components/OwnerPropertySwitcher';
import { Screen } from '@/components/Screen';
import { modulesForRole, roleLabels } from '@/modules';
import { DashboardData, loadDashboard } from '@/services/dashboard';
import { colors, radius, shadow } from '@/theme';

const ownerAttention = [
  { title: 'Gate Passes', detail: 'Requests pending', icon: 'exit-outline', moduleId: 'gate', count: '9', tone: '#0F766E', background: '#DDFBF3' },
  { title: 'Complaints', detail: 'Need attention', icon: 'construct-outline', moduleId: 'complaints', count: '3', tone: '#DC6803', background: '#FFF0D7' },
  { title: 'Documents', detail: 'To verify', icon: 'document-text-outline', moduleId: 'documents', count: '21', tone: '#2F62E6', background: '#E8EEFF' },
  { title: 'Requests', detail: 'New & in progress', icon: 'people-outline', moduleId: 'requests', count: '4', tone: '#7A35D8', background: '#F0E6FF' },
] as const;

const quickActions = [
  { label: 'Add floor', icon: 'layers-outline', moduleId: 'floors' },
  { label: 'Add room', icon: 'bed-outline', moduleId: 'rooms' },
  { label: 'Create due', icon: 'wallet-outline', moduleId: 'finance' },
  { label: 'Verify docs', icon: 'document-text-outline', moduleId: 'documents' },
  { label: 'Staff contact', icon: 'call-outline', moduleId: 'staff' },
  { label: 'New request', icon: 'file-tray-full-outline', moduleId: 'requests' },
] as const;

export default function DashboardScreen() {
  const { session } = useAuth();
  const router = useRouter();
  const { width } = useWindowDimensions();
  const role = session?.user.role ?? 'tenant';
  const [data, setData] = useState<DashboardData | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState('');
  const [quickOpen, setQuickOpen] = useState(false);
  const refresh = async (pull = false) => { if (!session) return; if (pull) setRefreshing(true); setError(''); try { setData(await loadDashboard(session)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load dashboard.'); } finally { setRefreshing(false); } };
  useEffect(() => { void refresh(); }, [session?.accessToken, session?.orgId, session?.user.role]);
  const modules = modulesForRole(role).slice(0, 4);
  const isCompact = width < 390;

  if (role === 'owner') {
    return <Screen contentStyle={[styles.ownerContent, isCompact && styles.ownerContentCompact]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void refresh(true)} tintColor={colors.forest} />}>
      <View style={styles.ownerHeader}><View style={styles.ownerHeaderCopy}><OwnerPropertySwitcher workspace={session?.workspace ?? 'City Complex'} /><Text style={[styles.ownerTitle, isCompact && styles.ownerTitleCompact]}>Hello, Owner</Text></View><Pressable accessibilityLabel="Open notifications" onPress={() => router.push('/notifications')} style={styles.ownerBell}><Ionicons color={colors.ink} name="notifications-outline" size={20} /><View style={styles.ownerDot} /></Pressable></View>
      <View style={styles.searchBar}><Ionicons color="#98A2B3" name="search-outline" size={18} /><TextInput editable={false} placeholder="Search modules, rooms, residents..." placeholderTextColor="#8F98AA" style={styles.searchInput} /><Pressable accessibilityLabel="Open quick actions" onPress={() => router.push({ pathname: '/module/[id]', params: { id: 'requests' } })} style={styles.sparkButton}><Ionicons color={colors.forest} name="sparkles" size={16} /></Pressable></View>
      <LinearGradient colors={['#07998E', '#006E73', '#054B5D']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={[styles.ownerHero, isCompact && styles.ownerHeroCompact, shadow]}>
        <View style={styles.heroGlow} /><View style={styles.heroTop}><View style={styles.heroIcon}><Ionicons color="#FFFFFF" name="trending-up" size={16} /></View><Text style={[styles.ownerHeroLabel, isCompact && styles.ownerHeroLabelCompact]}>{data?.headline ?? 'Your properties at a glance'}</Text></View><View style={[styles.buildingWrap, isCompact && styles.buildingWrapCompact]} pointerEvents="none"><View style={styles.buildingTall}>{[0, 1, 2, 3].map((item) => <View key={item} style={styles.window} />)}</View><View style={styles.buildingShort}>{[0, 1, 2].map((item) => <View key={item} style={styles.windowSmall} />)}</View></View>
        {data ? <View style={[styles.ownerMetrics, isCompact && styles.ownerMetricsCompact]}>{data.metrics.map(([value, label], index) => <View key={label} style={[styles.ownerMetric, index > 0 && styles.ownerMetricBorder]}><Text adjustsFontSizeToFit numberOfLines={1} style={[styles.ownerMetricValue, isCompact && styles.ownerMetricValueCompact]}>{value}</Text><Text numberOfLines={1} style={styles.ownerMetricLabel}>{label}</Text></View>)}</View> : <ActivityIndicator color="#fff" style={styles.ownerLoader} />}
      </LinearGradient>{!!error && <Text style={styles.error}>{error}</Text>}
      <View style={styles.ownerSectionHeader}><Text style={styles.ownerSectionTitle}>Quick access</Text><Pressable onPress={() => router.push('/modules')} style={styles.linkButton}><Text style={styles.ownerSectionLink}>All modules</Text><Ionicons color={colors.forest} name="chevron-forward" size={15} /></Pressable></View>
      <ScrollView horizontal contentContainerStyle={styles.ownerModuleRow} showsHorizontalScrollIndicator={false}>{modules.map((module) => <Pressable key={module.id} onPress={() => router.push({ pathname: '/module/[id]', params: { id: module.id } })} style={({ pressed }) => [styles.ownerModule, shadow, pressed && styles.pressed]}><View style={styles.ownerModuleIcon}><Ionicons color={colors.forest} name={module.icon as keyof typeof Ionicons.glyphMap} size={24} /></View><Text numberOfLines={2} style={styles.ownerModuleText}>{module.title}</Text></Pressable>)}</ScrollView>
      <View style={styles.ownerSectionHeader}><Text style={styles.ownerSectionTitle}>Needs attention</Text><Pressable onPress={() => router.push('/modules')} style={styles.linkButton}><Text style={styles.ownerSectionLink}>View all</Text><Ionicons color={colors.forest} name="chevron-forward" size={15} /></Pressable></View>
      <View style={[styles.ownerAttention, quickOpen && styles.ownerAttentionWithMenu, shadow]}>{ownerAttention.map((item, index) => <Pressable key={item.title} onPress={() => router.push({ pathname: '/module/[id]', params: { id: item.moduleId } })} style={[styles.ownerAttentionRow, index < ownerAttention.length - 1 && styles.ownerRowBorder]}><View style={styles.ownerAttentionIcon}><Ionicons color={colors.forest} name={item.icon} size={21} /></View><View style={styles.ownerAttentionCopy}><Text style={styles.ownerAttentionTitle}>{item.title}</Text><Text style={styles.ownerAttentionDetail}>{item.detail}</Text></View><View style={[styles.ownerCount, { backgroundColor: item.background }]}><Text style={[styles.ownerCountText, { color: item.tone }]}>{item.count}</Text></View><Ionicons color="#98A2B3" name="chevron-forward" size={18} /></Pressable>)}{quickOpen && <View style={[styles.quickMenu, shadow]}>{quickActions.map((action) => <Pressable key={action.label} onPress={() => { setQuickOpen(false); router.push({ pathname: '/module/[id]', params: { id: action.moduleId } }); }} style={styles.quickMenuItem}><View style={styles.quickMenuIcon}><Ionicons color={colors.forest} name={action.icon} size={16} /></View><Text style={styles.quickMenuText}>{action.label}</Text></Pressable>)}</View>}<Pressable onPress={() => setQuickOpen((value) => !value)} style={[styles.quickActions, quickOpen && styles.quickActionsOpen, shadow]}><Ionicons color="#FFFFFF" name={quickOpen ? 'close' : 'sparkles'} size={16} /><Text style={styles.quickActionsText}>Quick actions</Text></Pressable></View>
    </Screen>;
  }

  return <Screen refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void refresh(true)} tintColor={colors.forest} />}>
    <View style={styles.header}><View><Text style={styles.kicker}>{(session?.workspace ?? 'City Complex').toUpperCase()} · {roleLabels[role].toUpperCase()}</Text><Text style={styles.title}>Hello, {session?.user.name}</Text></View><Pressable onPress={() => router.push('/notifications')} style={styles.bell}><Ionicons color={colors.ink} name="notifications-outline" size={22} /><View style={styles.notificationDot} /></Pressable></View>
    <View style={styles.hero}>{data ? <><Text style={styles.heroLabel}>{data.headline.toUpperCase()}</Text><View style={styles.metrics}>{data.metrics.map(([value, label], index) => <View key={label} style={[styles.metric, index > 0 && styles.metricBorder]}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>)}</View></> : <ActivityIndicator color="#fff" />}</View>{!!error && <Text style={styles.error}>{error}</Text>}
    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Quick access</Text><Pressable onPress={() => router.push('/modules')}><Text style={styles.sectionLink}>All modules</Text></Pressable></View>
    <View style={styles.moduleRow}>{modules.map((module) => <Pressable key={module.id} onPress={() => router.push({ pathname: '/module/[id]', params: { id: module.id } })} style={styles.module}><View style={styles.moduleIcon}><Ionicons color={colors.forest} name={module.icon as keyof typeof Ionicons.glyphMap} size={20} /></View><Text numberOfLines={2} style={styles.moduleText}>{module.title}</Text></Pressable>)}</View>
    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Needs attention</Text><Text style={styles.sectionLink}>View all</Text></View>
    <View style={styles.attention}>{data?.attention.map(([title, detail, icon, moduleId], index) => <Pressable key={`${title}-${index}`} onPress={() => moduleId && router.push({ pathname: '/module/[id]', params: { id: moduleId } })} style={[styles.attentionRow, index < data.attention.length - 1 && styles.rowBorder]}><View style={styles.attentionIcon}><Ionicons color={colors.forest} name={icon as keyof typeof Ionicons.glyphMap} size={19} /></View><View style={styles.attentionCopy}><Text style={styles.attentionTitle}>{title}</Text><Text style={styles.attentionDetail}>{detail}</Text></View><Ionicons color={colors.muted} name="chevron-forward" size={17} /></Pressable>)}</View>
    <View style={styles.activity}><View style={styles.activityIcon}><Ionicons color={colors.success} name="pulse-outline" size={19} /></View><View><Text style={styles.activityTitle}>Workspace live</Text><Text style={styles.activityText}>Access is controlled by your role and property plan.</Text></View></View>
  </Screen>;
}

const styles = StyleSheet.create({
  ownerContent: { paddingBottom: 112, paddingHorizontal: 18 }, ownerContentCompact: { paddingHorizontal: 14 }, ownerHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 12, paddingTop: 18 }, ownerHeaderCopy: { flex: 1, paddingRight: 12 }, ownerKicker: { color: colors.forest, fontSize: 10, fontWeight: '900', letterSpacing: 2.1 }, ownerKickerCompact: { fontSize: 9, letterSpacing: 1.6 }, ownerTitle: { color: colors.ink, fontSize: 31, fontWeight: '900', letterSpacing: 0, marginTop: 5 }, ownerTitleCompact: { fontSize: 27 }, ownerBell: { alignItems: 'center', backgroundColor: colors.surface, borderColor: '#EEF1F4', borderRadius: 18, borderWidth: 1, height: 44, justifyContent: 'center', width: 44, ...shadow }, ownerDot: { backgroundColor: '#F97316', borderColor: colors.surface, borderRadius: 5, borderWidth: 2, height: 9, position: 'absolute', right: 9, top: 8, width: 9 },
  searchBar: { alignItems: 'center', backgroundColor: colors.surface, borderColor: '#E9EDF2', borderRadius: 20, borderWidth: 1, flexDirection: 'row', gap: 8, height: 44, marginBottom: 14, paddingLeft: 14, paddingRight: 5, ...shadow }, searchInput: { color: colors.ink, flex: 1, fontSize: 12, fontWeight: '700', height: 42, padding: 0 }, sparkButton: { alignItems: 'center', backgroundColor: colors.forestSoft, borderRadius: 16, height: 32, justifyContent: 'center', width: 32 },
  ownerHero: { borderRadius: 18, minHeight: 164, overflow: 'hidden', padding: 16 }, ownerHeroCompact: { minHeight: 152, padding: 14 }, heroGlow: { backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 120, height: 180, position: 'absolute', right: -84, top: -110, width: 220 }, heroTop: { alignItems: 'center', flexDirection: 'row', gap: 10 }, heroIcon: { alignItems: 'center', backgroundColor: 'rgba(214,168,79,0.42)', borderRadius: 10, height: 31, justifyContent: 'center', width: 31 }, ownerHeroLabel: { color: colors.surface, flex: 1, fontSize: 14, fontWeight: '900' }, ownerHeroLabelCompact: { fontSize: 13 }, buildingWrap: { alignItems: 'flex-end', bottom: 0, flexDirection: 'row', gap: 6, opacity: 0.42, position: 'absolute', right: 14 }, buildingWrapCompact: { opacity: 0.18, right: 4 }, buildingTall: { backgroundColor: '#32C8C0', borderRadius: 4, gap: 6, height: 92, padding: 10, width: 42 }, buildingShort: { backgroundColor: '#58D9D3', borderRadius: 4, gap: 6, height: 66, padding: 8, width: 36 }, window: { backgroundColor: 'rgba(0,65,75,0.55)', borderRadius: 2, height: 8, width: 16 }, windowSmall: { backgroundColor: 'rgba(0,65,75,0.48)', borderRadius: 2, height: 7, width: 14 },
  ownerMetrics: { flexDirection: 'row', marginTop: 38 }, ownerMetricsCompact: { marginTop: 34 }, ownerMetric: { flex: 1, minWidth: 0 }, ownerMetricBorder: { borderLeftColor: 'rgba(255,255,255,0.35)', borderLeftWidth: 1, paddingLeft: 8 }, ownerMetricValue: { color: colors.surface, fontSize: 27, fontWeight: '900', letterSpacing: 0 }, ownerMetricValueCompact: { fontSize: 23 }, ownerMetricLabel: { color: '#D2F0ED', fontSize: 10, fontWeight: '700', marginTop: 3 }, ownerLoader: { marginTop: 42 },
  ownerSectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, marginTop: 20 }, ownerSectionTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', letterSpacing: 0 }, linkButton: { alignItems: 'center', flexDirection: 'row', gap: 2 }, ownerSectionLink: { color: colors.forest, fontSize: 11, fontWeight: '900' }, ownerModuleRow: { flexDirection: 'row', gap: 8, paddingRight: 6 }, ownerModule: { alignItems: 'center', backgroundColor: colors.surface, borderColor: '#EEF1F4', borderRadius: 14, borderWidth: 1, height: 102, justifyContent: 'center', paddingHorizontal: 6, width: 82 }, ownerModuleIcon: { alignItems: 'center', backgroundColor: colors.forestSoft, borderRadius: 15, height: 44, justifyContent: 'center', width: 44 }, ownerModuleText: { color: colors.ink, fontSize: 10, fontWeight: '900', lineHeight: 13, marginTop: 8, minHeight: 26, textAlign: 'center' },
  ownerAttention: { backgroundColor: colors.surface, borderColor: '#EEF1F4', borderRadius: 15, borderWidth: 1, marginBottom: 16, paddingHorizontal: 10, paddingVertical: 2 }, ownerAttentionWithMenu: { marginBottom: 168 }, ownerAttentionRow: { alignItems: 'center', flexDirection: 'row', gap: 10, minHeight: 55 }, ownerRowBorder: { borderBottomColor: '#EBEEF2', borderBottomWidth: 1 }, ownerAttentionIcon: { alignItems: 'center', backgroundColor: colors.forestSoft, borderRadius: 11, height: 38, justifyContent: 'center', width: 38 }, ownerAttentionCopy: { flex: 1 }, ownerAttentionTitle: { color: colors.ink, fontSize: 13, fontWeight: '900' }, ownerAttentionDetail: { color: '#7B8496', fontSize: 10, fontWeight: '600', marginTop: 2 }, ownerCount: { alignItems: 'center', borderRadius: 11, height: 26, justifyContent: 'center', minWidth: 30, paddingHorizontal: 7 }, ownerCountText: { fontSize: 11, fontWeight: '900' }, quickMenu: { backgroundColor: colors.surface, borderColor: '#DCEBE7', borderRadius: 16, borderWidth: 1, bottom: -151, flexDirection: 'row', flexWrap: 'wrap', gap: 7, padding: 10, position: 'absolute', right: 0, width: 244, zIndex: 2 }, quickMenuItem: { alignItems: 'center', backgroundColor: '#F8FFFD', borderColor: '#E5F3EF', borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 38, paddingHorizontal: 8, width: '48%' }, quickMenuIcon: { alignItems: 'center', backgroundColor: colors.forestSoft, borderRadius: 8, height: 26, justifyContent: 'center', width: 26 }, quickMenuText: { color: colors.ink, flex: 1, fontSize: 10, fontWeight: '900' }, quickActions: { alignItems: 'center', backgroundColor: colors.forest, borderColor: '#69D0C6', borderRadius: 20, borderWidth: 1, bottom: -20, flexDirection: 'row', gap: 7, height: 41, justifyContent: 'center', minWidth: 140, paddingHorizontal: 14, position: 'absolute', right: 0, zIndex: 3 }, quickActionsOpen: { backgroundColor: '#095E57' }, quickActionsText: { color: colors.surface, fontSize: 12, fontWeight: '900' }, pressed: { opacity: 0.74 },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 22, paddingTop: 18 }, kicker: { color: colors.forest, fontSize: 9, fontWeight: '900', letterSpacing: 1.3 }, title: { color: colors.ink, fontSize: 25, fontWeight: '900', letterSpacing: -0.8, marginTop: 6 }, bell: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 15, borderWidth: 1, height: 45, justifyContent: 'center', width: 45 }, notificationDot: { backgroundColor: colors.warning, borderColor: colors.surface, borderRadius: 5, borderWidth: 2, height: 9, position: 'absolute', right: 9, top: 8, width: 9 },
  hero: { backgroundColor: colors.forest, borderRadius: radius.lg, padding: 20 }, heroLabel: { color: '#B6E5DD', fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, metrics: { flexDirection: 'row', marginTop: 19 }, metric: { flex: 1 }, metricBorder: { borderLeftColor: 'rgba(255,255,255,0.2)', borderLeftWidth: 1, paddingLeft: 14 }, metricValue: { color: colors.surface, fontSize: 22, fontWeight: '900', letterSpacing: -0.5 }, metricLabel: { color: '#C4E1DC', fontSize: 9, marginTop: 5 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, marginTop: 27 }, sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: '900', letterSpacing: -0.3 }, sectionLink: { color: colors.forest, fontSize: 11, fontWeight: '800' }, moduleRow: { flexDirection: 'row', gap: 8 }, module: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.sm, borderWidth: 1, flex: 1, minHeight: 96, paddingHorizontal: 5, paddingVertical: 12 }, moduleIcon: { alignItems: 'center', backgroundColor: colors.forestSoft, borderRadius: 11, height: 38, justifyContent: 'center', width: 38 }, moduleText: { color: colors.ink, fontSize: 9, fontWeight: '800', marginTop: 8, textAlign: 'center' },
  attention: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, paddingHorizontal: 15 }, attentionRow: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 15 }, rowBorder: { borderBottomColor: colors.border, borderBottomWidth: 1 }, attentionIcon: { alignItems: 'center', backgroundColor: colors.forestSoft, borderRadius: 11, height: 40, justifyContent: 'center', width: 40 }, attentionCopy: { flex: 1 }, attentionTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' }, attentionDetail: { color: colors.muted, fontSize: 10, marginTop: 4 },
  activity: { alignItems: 'center', backgroundColor: '#ECFDF3', borderRadius: radius.sm, flexDirection: 'row', gap: 11, marginTop: 18, padding: 14 }, activityIcon: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 10, height: 36, justifyContent: 'center', width: 36 }, activityTitle: { color: '#067647', fontSize: 11, fontWeight: '900' }, activityText: { color: '#42806A', fontSize: 9, marginTop: 3 }, error: { color: colors.danger, fontSize: 11, marginTop: 8 },
});
